### PR TITLE
UI Improved and made Responsive

### PR DESCRIPTION
**Pull request by 0xnmn**
Tic-tac-toe like UI adopted for this too. UI made responsive except scaling of the game frame, which is currently set to 800px wide. I guess the progress to make it fullscreen is already going on, under https://github.com/coding-blocks/angry-coders-game/issues/7. All other sections are responsive including buttons and editor. 

## Home
image

## ReadMe
image

## Responsive Buttons (Mobile View)
image

## Responsive Editor (Mobile View)
image

### CODE REVIEW

**Comment by prateek27** [comment]
http://angrycoders.codingblocks.com/
I merge the PR but the UI is behaving as expected. @hereisnaman  can you pls check.
issue

**Comment by 0xnmn** [comment]
@prateek27 then css changes: https://github.com/coding-blocks/angry-coders-game/pull/18/files#diff-23b024677d4732ee53b6d7bdc52e0fe2 are not being reflected in live version: 
image

**Comment by prateek27** [comment]
@hereisnaman  caching issue. Now resolved, everything working fine :) , approving your bounty for this.

**Comment by hereisnaman** [comment]
@prateek27 sir please give bounty of issue: https://github.com/coding-blocks/angry-coders-game/issues/13 to @asutosh7hota , I have already included his lines of code(changing editor's font size and family), so that there might not be merge conflicts. 

I have made a separate issue for UI changes, please add bounty for me there, I'll claim that.

**Pull request merged**
